starchat/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/thanks.html'), name="logout"),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

starchat/posts/urls.py
from django.urls import path, re_path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    re_path(r'by/(?P<username>[-\w]+)', views.UserPosts.as_view(), name='for_user'),
    re_path(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)', views.PostDetail.as_view(), name='single'),
    re_path(r'delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete')
]

starchat/starchat/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
]

starchat/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Star Social</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'starchat/css/master.css' %}">
</head>
<body>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5 mynav" role='navigation', id="navbar">
        <div class="container-fluid">
          <a class="navbar-brand mynav ps-5" href="{% url 'home' %}">Star Chat</a>
          <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon "></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end pe-5" id="navbarNav">
            <ul class="navbar-nav ps-5">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts:create' %}">Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'groups:create' %}">Create Group</a>
                    </li>
                    <li class="nav-item">
                        <form action="{% url 'logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class='nav-link'>Log Out</button>
                          </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
                    </li>
                {% endif %}
                    
            </ul>
          </div>
        </div>
      </nav>

    <div class="container mycontent">
        {% block content %}
        
        {% endblock content %}
    </div>
    <script type="text/javascript" src="{% static 'starchat/js/master.js'%}"></script>
</body>
</html>

starchat/templates/index.html
{% extends "base.html"%}

{% block content %}
    <h1>Welcome To StarChat</h1>
{% endblock content %}

starchat/templates/test.html
{% extends "base.html" %}
{% block content %}
    <h1>you are now logged in!</h1>
{% endblock content %}

starchat/templates/thanks.html
{% extends "base.html" %}
{% block content %}
    <h1>Thanks for visiting, come back soon!</h1>
{% endblock content %}