starchat/groups/urls.py
from django.urls import path, re_path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    re_path(r'posts/in/(?P<slug>[-\w]+)$', views.SingleGroup.as_view(), name='singleview'),
    re_path(r'join/(?P<slug>[-\w]+)$', views.JoinGroup.as_view(), name='join'),
    re_path(r'leave/(?P<slug>[-\w]+)$', views.LeaveGroup.as_view(), name='leave'),
]

starchat/posts/urls.py
from django.urls import path, re_path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    re_path(r'by/(?P<username>[-\w]+)', views.UserPosts.as_view(), name='for_user'),
    re_path(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)', views.PostDetail.as_view(), name='single'),
    re_path(r'delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete')
]

starchat/starchat/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
]

starchat/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
import misaka


from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()
# Create your models here.


class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("groups:singleview", kwargs={"slug": self.slug})

    class Meta:
        ordering = ['name']
    

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships' , on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    
    class Meta:
        unique_together = ('group', 'user')

starchat/groups/views.py
from typing import Any
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views import generic
from groups.models import Group
from django.shortcuts import get_object_or_404
from . import models
from django.contrib import messages
from django.db import IntegrityError
# Create your views here.


class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ("name", "description")
    model = Group

class SingleGroup(generic.DetailView):
    model = Group
    
class ListGroups(generic.ListView):
    model = Group
    
    
class JoinGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:singleview', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            models.GroupMember.objects.create(user=self.request.user, group=group)
        except IntegrityError:
            messages.warning(self.request, 'Warning already a member!')
        else:
            messages.success(self.request, 'You are now a member!')

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:singleview', kwargs={'slug': self.kwargs.get('slug')})
    
    def get(self, request, *args, **kwargs):
        
        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request, 'Sorry you are not in this group!')
        
        else:
            membership.delete()
            messages.success(self.request, 'You have left the group')
            
        return super().get(request, *args, **kwargs)

starchat/groups/templates/groups/group_base.html
{% extends "base.html" %}

{% block content %}
<div class='container'>
    <div class="row justify-content-evenly">
        {% block pregroup %}{% endblock pregroup %}
        {% block group_content %}{% endblock group_content %}
        {% block postgroup %}{% endblock postgroup %}
    </div>
</div>

{% endblock content %}

starchat/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<h1>{{group.name}}</h1>
<h2>Member Count: {{group.members.count}}</h2>

<div class="content">
    {% if user in group.members.all %}
        <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span>Leave</a>
    {% else %}
    <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span>Join</a>


    {% endif %}
</div>
{% endblock pregroup %}


{% block group_content %}
<div class="col-md-6">

    {% if group.posts.count == 0 %}
        <h2>No posts in this group yet!</h2>
    {% else %}
        {% for post in group.posts.all %}
            {% include "posts/_post.html" %}
        {% endfor %}
    {% endif %}

</div>

{% endblock group_content %}

starchat/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load django_bootstrap5 %}


{% block group_content %}

<div class="col-md-6">
    <div class="list-group">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-primary mb-3">
                    <div class="card-header"><h3>Create a new group!</h3></div>
                    <div class="card-body">
                        <form action="{% url 'groups:create'%}" method="post" id='groupForm'>
                            {% csrf_token %}
                            {%bootstrap_form form%}
                            <input type="submit" class="btn btn-primary btn-large" value="Create">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 
{% endblock group_content %}

starchat/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-6">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome back
			<a href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>
		</h2>

    {% endif %}
			<h3>Groups</h3>

			<p>Welcome to the Groups Page! Select a Group with a shared interest!</p>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New Group!</a>
	{% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-6">
	<div class="list-group">
		{% for group in object_list %}
		<div class="row">
			<div class="col-md-8">
			  <div class="card border-primary mb-3">
				<div class="card-header"><h3>{{ group.name }}</h3></div>
				<div class="card-body">
				  <p class="card-text">
					{{ group.description_html|safe }}
					<div class="col-md-8">
						<span class="badge rounded-pill bg-successbadge rounded-pill bg-success ms-3">{{ group.members.count }}</span> Member{{ group.members.count|pluralize }}
						<span class="badge rounded-pill bg-successbadge rounded-pill bg-success ms-3">{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}
					</div>
				  </p>
				  <a href="{% url 'groups:singleview' slug=group.slug %}" class="btn btn-primary ms-3">Go To Group</a>
				</div>
			  </div>
			</div>
		  </div>
		{% endfor %}
	</div>
</div>
{% endblock %}